version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - /
      # crates with [workspace] table are not recognized by the above 'directory: /'
      - /tests/no-std
      - /tests/no-std-rt
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    labels: []
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    labels: []
