#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0 OR MIT
# shellcheck disable=SC2207
set -CeEuo pipefail
IFS=$'\n\t'
trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
cd -- "$(dirname -- "$0")"/..

# Generates code based on target-spec.
#
# USAGE:
#    ./tools/target_spec.sh

build_file=src/gen/build.rs
mkdir -p -- "$(dirname -- "${build_file}")"

arm_but_thumb_mode=()
thumb_but_arm_mode=()
for target in $(rustc -Z unstable-options --print all-target-specs-json | jq -r '. | to_entries[] | if .value.arch == "arm" then .key else empty end'); do
    cfgs=$(rustc --print cfg --target "${target}")
    case "${target}" in
        thumb*)
            if ! grep -Fq '"thumb-mode"' <<<"${cfgs}"; then
                thumb_but_arm_mode+=("${target}")
            fi
            ;;
        *)
            if grep -Fq '"thumb-mode"' <<<"${cfgs}"; then
                arm_but_thumb_mode+=("${target}")
            fi
            ;;
    esac
done
if [[ ${#thumb_but_arm_mode[@]} -ne 0 ]]; then
    echo "thumb* but in arm mode...: ${thumb_but_arm_mode[*]}"
    exit 1
fi

cat >|"${build_file}" <<EOF
// SPDX-License-Identifier: Apache-2.0 OR MIT
// This file is @generated by ${0##*/}.
// It is not intended for manual editing.

#[rustfmt::skip]
pub(crate) static ARM_BUT_THUMB_MODE: &[&str] = &[
$(sed -E 's/^/    "/g; s/$/",/g' <<<"${arm_but_thumb_mode[*]}")
];
EOF
