name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  SEMIHOSTING_DENY_WARNINGS: 1
  # NB: sync with miri/msrv/test/tidy jobs' --features option and package.metadata.docs.rs.features field in Cargo.toml
  TEST_FEATURES: alloc,stdio,fs,args,time,random

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tidy:
    uses: taiki-e/github-actions/.github/workflows/tidy.yml@dc24bff2366e8ddeea5e0e4168df3d6f4b93f596 # 2026.8.8
    permissions:
      security-events: write # for github/codeql-action/*
    with:
      # We don't support x86_64, so use aarch64-unknown-linux-gnu instead.
      # TODO(mips): LLVM 23 bug https://github.com/llvm/llvm-project/issues/112010
      clippy-target: aarch64-unknown-linux-gnu,armv7-unknown-linux-gnueabihf,riscv64gc-unknown-linux-gnu,loongarch64-unknown-linux-gnu # ,mips64-unknown-linux-gnuabi64
      # NB: sync with env.TEST_FEATURES
      clippy-args: --features alloc,stdio,fs,args,time,random
      # TODO: workflow currently always runs doctest with the default target.
      clippy-doctest: false
  codegen:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/gen.yml@e6a1170cbd07eb898017958967912976fce18f2d # 2026.7.3
    permissions:
      contents: write # for creating branch for pr
    secrets:
      PR_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PR_TOKEN_APP_PRIVATE_KEY }}
  # We have some platform-independent code, so test them.
  test:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/rust-test.yml@e6a1170cbd07eb898017958967912976fce18f2d # 2026.7.3
    with:
      # We don't support x86_64, so use aarch64-unknown-linux-gnu instead.
      # TODO(mips): LLVM 23 bug https://github.com/llvm/llvm-project/issues/112010
      target: aarch64-unknown-linux-gnu # ,mips64-unknown-linux-gnuabi64
      # NB: sync with env.TEST_FEATURES
      features: --features alloc,stdio,fs,args,time,random
      optional-deps: ''
      build-args: --depth 2 --exclude-features panic-unwind,backtrace,trap-hlt,openocd-semihosting
      no-std: false # covered by no-std job
      miri-target: aarch64-unknown-linux-gnu
      # NB: sync with env.TEST_FEATURES
      miri-args: --features alloc,stdio,fs,args,time,random
      msrv-target: aarch64-unknown-linux-gnu,armv7-unknown-linux-gnueabihf,riscv64gc-unknown-linux-gnu
      # NB: sync with env.TEST_FEATURES
      msrv-args: --features alloc,stdio,fs,args,time,random

  no-std:
    needs: tidy
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: '1.64' # LLVM 14
          # - rust: '1.69' # LLVM 15
          # - rust: '1.72' # LLVM 16
          # - rust: '1.77' # LLVM 17
          # - rust: '1.81' # LLVM 18
          - rust: '1.83' # LLVM 19
          # - rust: '1.86' # LLVM 19
          # - rust: '1.90' # LLVM 20
          - rust: stable
          - rust: beta
          - rust: nightly
          # The behavior of semihosting somewhat depends on the behavior of the host system.
          - rust: nightly
            os: ubuntu-24.04-arm
          - rust: nightly
            os: macos-latest
          - rust: nightly
            os: windows-latest
    runs-on: ${{ matrix.os || 'ubuntu-24.04' }}
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: taiki-e/github-actions/free-device-space@e6a1170cbd07eb898017958967912976fce18f2d # 2026.7.3
        if: startsWith(matrix.os, 'ubuntu') || matrix.os == ''
      - uses: taiki-e/install-action@5b4d68e2e660441203ab128a23676f1e4faf1532 # v2.86.3
        with:
          tool: rust@${{ matrix.rust }}${{ (matrix.rust == 'stable' && (startsWith(matrix.os, 'ubuntu') || matrix.os == '')) && ',espup' || '' }}
          fallback: none
      - run: |
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          apt_packages=(libslirp0)
          llvm_version=$(rustc -vV | { grep -E '^LLVM version:' || true; } | cut -d' ' -f3)
          llvm_version="${llvm_version%%.*}"
          if [[ "${llvm_version}" -lt 17 ]]; then
            # pre-17 LLD doesn't support big-endian arm
            apt_packages+=(binutils-arm-none-eabi)
          fi
          retry sudo apt-get -o Acquire::Retries=10 -qq update
          retry sudo apt-get -o Acquire::Retries=10 -o Dpkg::Use-Pty=0 install -y --no-install-recommends "${apt_packages[@]}"
          # https://github.com/taiki-e/dockerfiles/pkgs/container/qemu-user
          # TODO: "Bail out! ERROR:target/arm/cpregs-omap-stub.c:9:define_omap_cp_regs: code should not be reached" error with ti925t
          retry docker create --name qemu-user ghcr.io/taiki-e/qemu-user:11.0
          mkdir -p -- qemu-user
          docker cp -- qemu-user:/usr/bin qemu-user/bin
          docker rm -f -- qemu-user >/dev/null
          sudo mv -- qemu-user/bin/qemu-* /usr/local/bin/
          rm -rf -- ./qemu-user
          qemu-arm --version
          if [[ "${RUST}" == "stable" ]]; then
            retry espup install --targets esp32
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST: ${{ matrix.rust }}
        if: startsWith(matrix.os, 'ubuntu') || matrix.os == ''
      - run: |
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          # Patched QEMU for MIPS semihosting
          retry curl --proto '=https' --tlsv1.2 -fsSL --retry 10 https://github.com/taiki-e/qemu/releases/download/patched-11.0.0/qemu-"${OS}".tar.xz \
            | tar xJf -
          sudo cp -r -- qemu/. /usr/local/
          rm -rf -- ./qemu
          printf 'MIPS_QEMU_SYSTEM_BIN_DIR=/usr/local/bin\n' >>"${GITHUB_ENV}"
          # Patched QEMU for LoongArch semihosting
          retry curl --proto '=https' --tlsv1.2 -fsSL --retry 10 https://github.com/taiki-e/qemu/releases/download/loongarch-semi-10.1.5/qemu-"${OS}".tar.xz \
            | tar xJf -
          sudo mv -- qemu /usr/local/qemu-loongarch-semi
          printf 'LOONGARCH_QEMU_BIN_DIR=/usr/local/qemu-loongarch-semi/bin\n' >>"${GITHUB_ENV}"
        env:
          OS: ${{ matrix.os || 'ubuntu-24.04' }}
        if: startsWith(matrix.os, 'ubuntu') || matrix.os == '' || startsWith(matrix.os, 'macos')
      - run: |
          C:/msys64/usr/bin/pacman -S --noconfirm mingw-w64-ucrt-x86_64-qemu
          printf '%s\n' 'C:\msys64\ucrt64\bin' >>"${GITHUB_PATH}"
          C:/msys64/ucrt64/bin/qemu-system-arm --version
        if: startsWith(matrix.os, 'windows')
      # Avoid needless git fetch
      - run: sed -Ei '/^unwinding = .*/d' Cargo.toml
        working-directory: tests/no-std
        if: matrix.rust != 'nightly'
      # syn 2.0.107 & quote 1.0.42 & proc-macro2 1.0.104 requires Rust 1.68.
      # unicode-ident 1.0.23 requires Rust 1.71.
      # cortex-m-rt 0.7.6 requires Rust 1.85.
      - run: |
          cargo generate-lockfile
          cargo update -p proc-macro2 --precise 1.0.103
          cargo update -p quote --precise 1.0.41
          cargo update -p syn@2.0.119 --precise 2.0.106
          cargo update -p unicode-ident --precise 1.0.22
          cargo update -p cortex-m-rt --precise 0.7.5
        working-directory: tests/no-std
        if: startsWith(matrix.rust, '1.6') || startsWith(matrix.rust, '1.7') || startsWith(matrix.rust, '1.8')
      - run: tools/no-std.sh
        env:
          ALL_TARGETS_MUST_BE_AVAILABLE: ${{ matrix.rust == 'nightly' || '' }}
      - run: TEST_RUNNER=qemu-user tools/no-std.sh
        if: startsWith(matrix.os, 'ubuntu') || matrix.os == ''
      - run: cargo +esp build --target xtensa-esp32-none-elf -Z build-std=core,alloc --features "${TEST_FEATURES},openocd-semihosting"
        if: matrix.rust == 'stable' && (startsWith(matrix.os, 'ubuntu') || matrix.os == '')
