name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  SEMIHOSTING_DENY_WARNINGS: 1
  # NB: sync with miri/msrv/test/tidy jobs' --features option and package.metadata.docs.rs.features field in Cargo.toml
  TEST_FEATURES: alloc,stdio,fs,args,time,random

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  miri:
    uses: taiki-e/github-actions/.github/workflows/miri.yml@main
    with:
      # We don't support x86_64, so use aarch64-unknown-linux-gnu instead.
      target: aarch64-unknown-linux-gnu
      # NB: sync with env.TEST_FEATURES
      args: --features alloc,stdio,fs,args,time,random
  msrv:
    uses: taiki-e/github-actions/.github/workflows/msrv.yml@main
    with:
      # We don't support x86_64, so use aarch64-unknown-linux-gnu instead.
      target: aarch64-unknown-linux-gnu,armv7-unknown-linux-gnueabihf,riscv64gc-unknown-linux-gnu
      # NB: sync with env.TEST_FEATURES
      args: --features alloc,stdio,fs,args,time,random
  # We have some platform-independent code, so test them.
  test:
    uses: taiki-e/github-actions/.github/workflows/test.yml@main
    with:
      # We don't support x86_64, so use aarch64-unknown-linux-gnu instead.
      target: aarch64-unknown-linux-gnu,mips64-unknown-linux-gnuabi64
      # NB: sync with env.TEST_FEATURES
      features: --features alloc,stdio,fs,args,time,random
      optional-deps: ''
      build-args: --depth 2 --exclude-features panic-unwind,backtrace,trap-hlt,openocd-semihosting
      no-std: false # covered by no-std job
  tidy:
    uses: taiki-e/github-actions/.github/workflows/tidy.yml@main
    permissions:
      contents: write # for creating branch for pr
      pull-requests: write # unused (used in `codegen-automerge: true` case)
      security-events: write # for github/codeql-action/*
    secrets:
      PR_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PR_TOKEN_APP_PRIVATE_KEY }}
    with:
      # We don't support x86_64, so use aarch64-unknown-linux-gnu instead.
      clippy-target: aarch64-unknown-linux-gnu,armv7-unknown-linux-gnueabihf,riscv64gc-unknown-linux-gnu,mips64-unknown-linux-gnuabi64,loongarch64-unknown-linux-gnu
      # NB: sync with env.TEST_FEATURES
      clippy-args: --features alloc,stdio,fs,args,time,random
      # TODO: workflow currently always runs doctest with the default target.
      clippy-doctest: false

  no-std:
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: '1.64' # LLVM 14
          # - rust: '1.69' # LLVM 15
          # - rust: '1.72' # LLVM 16
          # - rust: '1.77' # LLVM 17
          # - rust: '1.81' # LLVM 18
          - rust: '1.83' # LLVM 19
          # - rust: '1.86' # LLVM 19
          # - rust: '1.90' # LLVM 20
          - rust: stable
          - rust: beta
          - rust: nightly
          # The behavior of semihosting somewhat depends on the behavior of the host system.
          - rust: nightly
            os: ubuntu-24.04-arm
          - rust: nightly
            os: macos-latest
          - rust: nightly
            os: windows-latest
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: taiki-e/github-actions/free-device-space@main
        if: startsWith(matrix.os, 'ubuntu') || matrix.os == ''
      - uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: ${{ matrix.rust }}
      - uses: taiki-e/install-action@v2
        with:
          tool: espup
          fallback: none
        if: matrix.rust == 'stable' && (startsWith(matrix.os, 'ubuntu') || matrix.os == '')
      - run: |
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          llvm_version=$(rustc -vV | { grep -E '^LLVM version:' || true; } | cut -d' ' -f3)
          llvm_version="${llvm_version%%.*}"
          if [[ "${llvm_version}" -lt 17 ]]; then
            # pre-17 LLD doesn't support big-endian arm
            retry sudo apt-get -o Acquire::Retries=10 -qq update
            retry sudo apt-get -o Acquire::Retries=10 -o Dpkg::Use-Pty=0 install -y --no-install-recommends binutils-arm-none-eabi
          fi
          # https://github.com/taiki-e/dockerfiles/pkgs/container/qemu-user
          retry docker create --name qemu-user ghcr.io/taiki-e/qemu-user
          mkdir -p -- qemu-user
          docker cp -- qemu-user:/usr/bin qemu-user/bin
          docker rm -f -- qemu-user >/dev/null
          sudo mv -- qemu-user/bin/qemu-* /usr/local/bin/
          rm -rf -- ./qemu-user
          qemu-arm --version
          if [[ "${RUST}" == "stable" ]]; then
            retry espup install --targets esp32
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST: ${{ matrix.rust }}
        if: startsWith(matrix.os, 'ubuntu') || matrix.os == ''
      - run: |
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          # Patched QEMU for MIPS semihosting
          retry curl --proto '=https' --tlsv1.2 -fsSL https://github.com/taiki-e/qemu/releases/download/patched-11.0.0-rc0/qemu-"${OS}".tar.xz \
            | tar xJf -
          sudo cp -r -- qemu/. /usr/local/
          rm -rf -- ./qemu
          printf '%s\n' "MIPS_QEMU_SYSTEM_BIN_DIR=/usr/local/bin" >>"${GITHUB_ENV}"
          # Patched QEMU for LoongArch semihosting
          retry curl --proto '=https' --tlsv1.2 -fsSL https://github.com/taiki-e/qemu/releases/download/loongarch-semi-10.1.5/qemu-"${OS}".tar.xz \
            | tar xJf -
          sudo mv -- qemu /usr/local/qemu-loongarch-semi
          printf '%s\n' "LOONGARCH_QEMU_BIN_DIR=/usr/local/qemu-loongarch-semi/bin" >>"${GITHUB_ENV}"
        env:
          OS: ${{ matrix.os || 'ubuntu-24.04' }}
        if: startsWith(matrix.os, 'ubuntu') || matrix.os == '' || startsWith(matrix.os, 'macos')
      - run: |
          C:/msys64/usr/bin/pacman -S --noconfirm mingw-w64-ucrt-x86_64-qemu
          printf '%s\n' 'C:\msys64\ucrt64\bin' >>"${GITHUB_PATH}"
          C:/msys64/ucrt64/bin/qemu-system-arm --version
        if: startsWith(matrix.os, 'windows')
      # Avoid needless git fetch
      - run: sed -Ei '/^unwinding = .*/d' Cargo.toml
        working-directory: tests/no-std
        if: matrix.rust != 'nightly'
      # syn 2.0.107 & quote 1.0.42 & proc-macro2 1.0.104 requires Rust 1.68.
      # unicode-ident 1.0.23 requires Rust 1.71.
      - run: |
          cargo generate-lockfile
          cargo update -p proc-macro2 --precise 1.0.103
          cargo update -p quote --precise 1.0.41
          cargo update -p syn --precise 2.0.106
          cargo update -p unicode-ident --precise 1.0.22
        working-directory: tests/no-std
        if: matrix.rust == '1.64'
      - run: tools/no-std.sh
        env:
          ALL_TARGETS_MUST_BE_AVAILABLE: ${{ matrix.rust == 'nightly' || '' }}
      - run: TEST_RUNNER=qemu-user tools/no-std.sh
        if: startsWith(matrix.os, 'ubuntu') || matrix.os == ''
      - run: cargo +esp build --target xtensa-esp32-none-elf -Z build-std=core,alloc --features "${TEST_FEATURES},openocd-semihosting"
        if: matrix.rust == 'stable' && (startsWith(matrix.os, 'ubuntu') || matrix.os == '')

  no-std-hexagon:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: taiki-e/github-actions/install-rust@nightly
      - run: |
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          retry sudo apt-get -o Acquire::Retries=10 -qq update
          retry sudo apt-get -o Acquire::Retries=10 -o Dpkg::Use-Pty=0 install -y --no-install-recommends \
            libc++1-14 \
            libfdt1 \
            libiscsi7 \
            libjack0 \
            libpulse0 \
            libslirp0 \
            libsndio7.0 \
            liburing2
          # https://github.com/quic/toolchain_for_hexagon/releases
          llvm_version=22.1.0
          mkdir -p -- clang-hexagon
          retry curl --proto '=https' --tlsv1.2 -fsSL --retry 10 --retry-all-errors "https://artifacts.codelinaro.org/artifactory/codelinaro-toolchain-for-hexagon/${llvm_version}_/clang+llvm-${llvm_version}-cross-hexagon-unknown-linux-musl.tar.zst" \
            | tar xf - --zstd --strip-components 2 -C clang-hexagon
          sudo mv -- clang-hexagon /usr/local/clang-hexagon
          printf '%s\n' "CARGO_TARGET_HEXAGON_UNKNOWN_NONE_ELF_LINKER=/usr/local/clang-hexagon/bin/hexagon-unknown-none-elf-clang" >>"${GITHUB_ENV}"
          printf '%s\n' "CARGO_TARGET_HEXAGON_UNKNOWN_LINUX_MUSL_LINKER=/usr/local/clang-hexagon/bin/hexagon-unknown-linux-musl-clang" >>"${GITHUB_ENV}"
          printf '%s\n' "HEXAGON_QEMU_BIN_DIR=/usr/local/clang-hexagon/bin" >>"${GITHUB_ENV}"
      # Avoid needless git fetch
      - run: sed -Ei '/^unwinding = .*/d' Cargo.toml
        working-directory: tests/no-std
      - run: tools/no-std.sh hexagon-unknown-none-elf
      # TODO(hexagon):
      # With hexagon-unknown-none-elf, I got https://gitlab.com/qemu-project/qemu/-/work_items/805
      # With hexagon-unknown-linux-musl, I got:
      #   + /usr/local/clang-hexagon/bin/qemu-hexagon -cpu v68 -L /usr/local/clang-hexagon/target/hexagon-unknown-linux-musl ../../target/hexagon-unknown-linux-musl/debug/no-std-test a '' ''\''c d'\'''
      #   22558 set_tid_address(0x4093e734) = 22558
      #   22558 brk(NULL) = 0x08020000
      #   22558 brk(0x08040000) = 0x08040000
      #   22558 mmap2(0x08020000,65536,PROT_NONE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED,-1,0) = 0x08020000
      #   --- SIGSEGV {si_signo=SIGSEGV, si_code=2, si_addr=0x08000000} ---
      # - run: TEST_RUNNER=qemu-user tools/no-std.sh hexagon-unknown-linux-musl
