name: Release

permissions:
  contents: read

on:
  push:
    tags:
      - v[0-9]+.*

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

jobs:
  create-release:
    if: github.repository_owner == 'taiki-e'
    uses: taiki-e/github-actions/.github/workflows/create-release.yml@main
    with:
      # We don't support x86_64, so use aarch64-unknown-linux-gnu instead.
      target: aarch64-unknown-linux-gnu
    permissions:
      contents: write # for taiki-e/create-gh-release-action
      id-token: write # for rust-lang/crates-io-auth-action
    secrets: inherit
